### ISSUE TITLE
spark-dependencies cannot generate DAG information

### ISSUE THREAD

**Issue by 2005wind** [jaegertracing/spark-dependencies#103]
Hello
I use the following components:

jaeger-operator:1.20.0
jaeger-collector:1.20.0
storage use es 7.10.

Now I found we use data format[Prefix-jaeger-span-000001] to store the index .
but  spark-dependencies use prefix-jaeger-span-YYYY-MM-DD

Is this expected? Can it be adjusted? How to deal with it? Thank you.
Below is the configuration of my jaeger operator.

```
  storage:
    cassandraCreateSchema: {}
    dependencies:
      enabled: true
      resources: {}
      schedule: 55 23 * * *
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: '1'
          memory: 16Gi
      storage: {}
    esIndexCleaner:
      enabled: false
      numberOfDays: 1000
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      conditions: '{"max_age": "1d"}'
      readTTL: 168h
      resources: {}
      schedule: 55 23 * * *
    options:
      es:
        create-index-templates: true
        index-prefix: qa
        max-num-spans: 10000
        max-span-age: 72h0m0s
        server-urls: >-
          https://XXXXXXXXXX:443
        timeout: 120s
        use-aliases: true
        version: 7
    secretName: jaeger-secret
    type: elasticsearch
  strategy: production
```
